---
sudo: false
language: ruby
cache: bundler
bundler_args: '--without system_tests development'

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

matrix:
  fast_finish: true
  include:
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 5" CHECK=test
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 6" CHECK=test
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 7" CHECK=test

notifications:
  email: false
